### 全局通用参数
complete -c xmake -s q -l quiet -d 'Quiet operation.'
complete -c xmake -s y -l yes -d 'Input yes by default if need user confirm.'
complete -c xmake -l confirm -x -a yes -d 'Input yes by default if need user confirm.'
complete -c xmake -l confirm -x -a no -d 'Input no by default if need user confirm.'
complete -c xmake -l confirm -x -a def -d 'Input def by default if need user confirm.'
complete -c xmake -l confirm -x -d 'Input the given result if need user confirm.'
complete -c xmake -s v -l verbose -d 'Print lots of verbose information for users.'
complete -c xmake -l root -d 'Allow to run xmake as root.'
complete -c xmake -s D -l diagnosis -d 'Print lots of diagnosis information (backtrace, check info ..) only for developers.'
complete -c xmake -l version -d 'Print the version number and exit.'
complete -c xmake -s h -l help -d 'Print this help message and exit.'
complete -c xmake -s F -l file -r -F -d 'Read a given xmake.lua file.'
complete -c xmake -s P -l project -r -d 'Change to the given project directory.'
