#!/usr/bin/env bash
# 自动升级 Microsoft Edge Driver

function run_upgrade {
  # 正式执行升级任务
  echo -e "\e[33m任务详情：$1 ==> $2\e[0m"
  if [ ! -d "/opt/microsoft/msedgedriver" ]; then
    sudo mkdir -pv /opt/microsoft/msedgedriver
  fi
  sudo rm -rvf "/opt/microsoft/msedgedriver/*"
  if [ -f "/tmp/edgedriver_linux64_$1.zip" ]; then
    sudo rm -rvf "/tmp/edgedriver_linux64_$1.zip"
  fi
  if [ ! -f "/tmp/edgedriver_linux64_$2.zip" ]; then
    sudo wget -O "/tmp/edgedriver_linux64_$2.zip" \
      "https://msedgedriver.azureedge.net/$2/edgedriver_linux64.zip"
  fi
  sudo unzip "/tmp/edgedriver_linux64_$2.zip" -d "/opt/microsoft/msedgedriver/"
  sudo rm -rvf "/tmp/edgedriver_linux64_$2.zip"
  return $?
}

# 权限检查
CURRENT_GROUPS="$(groups $USER)"
if [[ "$CURRENT_GROUPS" == *"root"* || "$CURRENT_GROUPS" == *"sudo"* ]]; then
  :
else
  echo -e "\e[31m本权限需要超级用户权限！\e[0m"
  exit 1
fi

# 检查 Edge & Driver 版本
stable="$(microsoft-edge-stable --version 2> /dev/null | awk '{print $3}')"
driver="$(/opt/microsoft/msedgedriver/msedgedriver --version 2> /dev/null | awk '{print $4}')"
if [ -z "$stable" ]; then
  echo -e "\e[31m未安装 Microsoft Edge Stable ！"
  exit 1
elif [ -z "$driver" ]; then
  # 没有检测到 Driver
  echo -e "\e[31m未检测到驱动器版本！可能您尚未安装 Microosft Edge Driver ？"
  echo -e "\e[33m是否下载并安装 Microsoft Edge Driver ？[Y/N]\e[0m"
  read response
  if [ -z "$response" ]; then
    response="Y"
  fi
  if [[ "$response" == "y" || "$response" == "Y" ]]; then
    driver="Not installed"
    run_upgrade "$driver" "$stable"
    if [ $? ]; then
      echo -e "\e[32m已成功安装 Microsoft Edge Driver！\e[0m"
      echo -e "\e[32m当前驱动版本：$stable\e[0m"
      echo -e "\e[32m安装路径：/opt/microsoft/msedge/driver/msedgedriver\e[0m"
      exit 0
    else
      echo -e "\e[31m驱动程序安装失败！\e[0m"
      exit 1
    fi
  fi
elif [ "$stable" == "$driver" ]; then
  # 版本匹配
  echo -e "\e[32m当前驱动程序与主程序版本匹配！\e[0m"
  exit 0
else
  # 版本不匹配
  echo -e "\e[33m检测到新版本！\e[0m"
  run_upgrade "$driver" "$stable"
  exit $?
fi
